const SOURCES={
  reacenti:{id:'reacenti',name:"Reacenti's Collection",shortName:'Kumu',spreadsheetId:process.env.SOURCE_REACENTI_ID,gid:process.env.SOURCE_REACENTI_GID||'601608137'},
  exclusives:{id:'exclusives',name:'Exclusives',shortName:'Exclusives',spreadsheetId:process.env.SOURCE_EXCLUSIVES_ID,gid:process.env.SOURCE_EXCLUSIVES_GID||'601608137'},
  concerts:{id:'concerts',name:'Concerts',shortName:'Concerts',spreadsheetId:process.env.SOURCE_CONCERTS_ID,gid:process.env.SOURCE_CONCERTS_GID||'601608137'},
  misc:{id:'misc',name:'Misc Appearances',shortName:'Misc',spreadsheetId:process.env.SOURCE_MISC_ID,gid:process.env.SOURCE_MISC_GID||'0'},
  fancams:{id:'fancams',name:'BINI Fancams',shortName:'Fancams',spreadsheetId:process.env.SOURCE_FANCAMS_ID,gid:process.env.SOURCE_FANCAMS_GID||'0'}
};
for(const s of Object.values(SOURCES)) if(!s.spreadsheetId) throw new Error(`Missing spreadsheet ID for source: ${s.id}`);
const cache=new Map();const refreshing=new Map();const health=new Map();
const CACHE_TTL=10*60*1000,STALE_TTL=60*60*1000,REQUEST_TIMEOUT=15000;
function csvUrl(s){return `https://docs.google.com/spreadsheets/d/${s.spreadsheetId}/export?format=csv&gid=${s.gid}`}
function parseCSV(text){const rows=[];let row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const ch=text[i],next=text[i+1];if(ch==='"'){if(quoted&&next==='"'){cell+='"';i++}else quoted=!quoted;continue}if(ch===','&&!quoted){row.push(cell);cell='';continue}if((ch==='\n'||ch==='\r')&&!quoted){if(ch==='\r'&&next==='\n')i++;row.push(cell);cell='';if(row.some(v=>v.trim()))rows.push(row);row=[];continue}cell+=ch}if(cell.length||row.length){row.push(cell);if(row.some(v=>v.trim()))rows.push(row)}if(!rows.length)return[];const headers=rows[0].map(h=>h.trim());return rows.slice(1).map(vals=>Object.fromEntries(headers.map((h,i)=>[h,vals[i]??''])))}
function clean(v=''){return String(v).replace(/\s+/g,' ').trim()}
function tags(v=''){return v.split(',').map(clean).filter(Boolean)}
function htmlImage(v=''){const m=v.match(/<img[^>]+src=["']([^"']+)["']/i);return m?.[1]||null}
function youtubeId(url=''){try{const u=new URL(url);if(u.hostname==='youtu.be')return u.pathname.slice(1).split('/')[0]||'';return u.searchParams.get('v')||(u.pathname.startsWith('/shorts/')?u.pathname.split('/')[2]:'')||(u.pathname.startsWith('/embed/')?u.pathname.split('/')[2]:'')}catch{return''}}
function isVideo(row){return Boolean(clean(row.duration)||clean(row.link)||clean(row.ORIGINAL))}
function canonicalKey(v){if(v.youtubeId)return `yt:${v.youtubeId}`;const title=clean(v.title).toLowerCase().replace(/[^a-z0-9]+/g,'-');return `${title}|${v.date||''}|${v.duration||''}`}
function normalizeRow(row,source,index){const link=clean(row.link),original=clean(row.ORIGINAL),url=link||original||null;const yt=youtubeId(url||'');const out={id:clean(row.uid)||`${source.id}-${index}`,sourceId:source.id,sourceName:source.name,type:isVideo(row)?'video':'article',title:clean(row.title),chapter:clean(row.chapter),duration:clean(row.duration)||null,description:row.description||'',tags:tags(row.tags),thumbnail:clean(row.thumbnail)||null,descriptionImage:htmlImage(row.description),youtubeId:yt||null,date:clean(row.date)||null,year:Number((clean(row.date)||'').slice(0,4))||null,url,canonicalKey:''};out.canonicalKey=canonicalKey(out);return out}
function sortVideos(v){return [...v].sort((a,b)=>(Date.parse(b.date||'')||0)-(Date.parse(a.date||'')||0)||a.title.localeCompare(b.title,undefined,{numeric:true,sensitivity:'base'}))}
async function fetchText(url){const c=new AbortController();const t=setTimeout(()=>c.abort(),REQUEST_TIMEOUT);try{const r=await fetch(url,{signal:c.signal,headers:{'User-Agent':'BINI-Vault/1.0'}});if(!r.ok)throw new Error(`Google Sheets returned HTTP ${r.status}`);return await r.text()}finally{clearTimeout(t)}}
export function getSources(){return Object.values(SOURCES).map(({spreadsheetId,gid,...pub})=>pub)}
async function refreshSource(sourceId){if(refreshing.has(sourceId))return refreshing.get(sourceId);const p=(async()=>{const source=SOURCES[sourceId];const started=Date.now();health.set(sourceId,{...health.get(sourceId),status:'refreshing',lastAttempt:new Date().toISOString()});try{const raw=parseCSV(await fetchText(csvUrl(source)));const normalized=raw.map((r,i)=>normalizeRow(r,source,i));const videos=sortVideos(normalized.filter(v=>v.type==='video'));const data={source:getSources().find(v=>v.id===sourceId),count:normalized.length,videoCount:videos.length,articleCount:normalized.length-videos.length,videos,articles:normalized.filter(v=>v.type==='article'),fetchedAt:new Date().toISOString()};cache.set(sourceId,{cachedAt:Date.now(),data});health.set(sourceId,{status:'healthy',lastAttempt:new Date().toISOString(),lastSuccess:data.fetchedAt,latencyMs:Date.now()-started,videoCount:videos.length});return data}catch(e){health.set(sourceId,{status:'error',lastAttempt:new Date().toISOString(),lastError:e.message,latencyMs:Date.now()-started,videoCount:cache.get(sourceId)?.data?.videoCount||0});throw e}})().finally(()=>refreshing.delete(sourceId));refreshing.set(sourceId,p);return p}
export async function fetchSource(sourceId,{force=false}={}){if(!SOURCES[sourceId])throw new Error(`Unknown source: ${sourceId}`);const existing=cache.get(sourceId);if(!force&&existing){const age=Date.now()-existing.cachedAt;if(age<CACHE_TTL)return {...existing.data,cached:true,stale:false};if(age<STALE_TTL){if(!refreshing.has(sourceId))refreshSource(sourceId).catch(()=>{});return {...existing.data,cached:true,stale:true}}}return {...await refreshSource(sourceId),cached:false,stale:false}}
export async function fetchCatalog({sources,q='',tag='',year='',page=1,limit=24,sort='newest'}={}){const ids=sources?.length?sources:Object.keys(SOURCES);const results=await Promise.all(ids.map(id=>fetchSource(id)));const query=q.trim().toLowerCase(),tagQuery=tag.trim().toLowerCase(),yearNum=Number(year)||null;const dedup=new Map();for(const r of results){for(const v of r.videos){if(query&&!`${v.title} ${v.description||''} ${v.sourceName} ${v.date||''} ${(v.tags||[]).join(' ')}`.toLowerCase().includes(query))continue;if(tagQuery&&!(v.tags||[]).some(t=>t.toLowerCase()===tagQuery))continue;if(yearNum&&v.year!==yearNum)continue;const existing=dedup.get(v.canonicalKey);if(existing){existing.alternateSources=[...(existing.alternateSources||[]),{id:v.sourceId,name:v.sourceName,url:v.url}]}else{dedup.set(v.canonicalKey,{...v,alternateSources:[]})}}}let videos=[...dedup.values()];if(sort==='oldest')videos.sort((a,b)=>(Date.parse(a.date||'')||0)-(Date.parse(b.date||'')||0)||a.title.localeCompare(b.title,undefined,{numeric:true,sensitivity:'base'}));else if(sort==='title')videos.sort((a,b)=>a.title.localeCompare(b.title,undefined,{numeric:true,sensitivity:'base'}));else videos=sortVideos(videos);const start=(Math.max(1,page)-1)*limit;return{count:videos.length,page,limit,hasMore:start+limit<videos.length,videos:videos.slice(start,start+limit),fetchedAt:new Date().toISOString()}}
export async function findVideo(sourceId,id){const data=await fetchSource(sourceId);return data.videos.find(v=>v.id===id)||null}
export function getCacheInfo(){return Object.fromEntries([...cache.entries()].map(([id,v])=>[id,{cachedAt:v.cachedAt,ageMs:Date.now()-v.cachedAt,videoCount:v.data.videoCount,refreshing:refreshing.has(id),stale:Date.now()-v.cachedAt>=CACHE_TTL}]))}
export function getSourceHealth(){return Object.values(SOURCES).map(s=>({id:s.id,name:s.name,...(health.get(s.id)||{status:cache.has(s.id)?'healthy':'idle',videoCount:cache.get(s.id)?.data?.videoCount||0})}))}
